### ISSUE TITLE
Remove unused deps

### ISSUE THREAD

**Issue by MaxMilton** [sveltejs/sapper-template-rollup#3]
`rollup-plugin-loadz0r` is no longer being used as of commit https://github.com/sveltejs/sapper-template-rollup/commit/1b9dfffc5e4ce0ce19097b146b86f596ce3ee8db and so should be removed.

I couldn't find any reference to `chokidar` in the project either. I'm able to build and dev as normal when it's removed so perhaps that's another left over dep.

**Comment by Rich-Harris** [comment]
Thanks — removed loadz0r. chokidar *is* necessary, sadly — Rollup uses it if present, otherwise it uses `fs.watch` which is buggier than an ant farm.

**Comment by MaxMilton** [comment]
I see, thanks that's good to know! I'm going to add `chokidar` to some of my other rollup projects :smile:
