### ISSUE TITLE
Doesn't compile when using regexp routes

### ISSUE THREAD

**Issue by elcobvg** [sveltejs/sapper-template-rollup#6]
I get these errors when trying to fire up my project with rollup:

```
✗ server
no parsers registered for: "].htm"
✗ client
no parsers registered for: "].htm"
```

Which very likely has to do with the fact that I'm using regexp patterns in my routes. The starter app has no such problems.

(FWIW, the errors come from snapdragon:parser)

**Comment by Rich-Harris** [comment]
This can be fixed by adding the `watch.chokidar.disableGlobbing = true` option, which I've added to the default configs over on sapper-template#rollup, which replaces this repo: https://github.com/sveltejs/sapper-template/tree/rollup/rollup
